- src/js/components/Table.js
Fix expanding of options not working
The clicking was only being processed when the input changed causing odd behaviour
Prevent user from setting 0 or negative amount of entries in a table
additionally, prevent the internal state becoming negative if the user would keep pressing '-x',
otherwise, when clicking '+x' the internal state would still be a negative amount and user needs to press
an unknown amount of '+x' before changes are visible
allow internal state to be 0, but always request at least 1
if user adds 5 again, new value should be 5 not 6 so we can't just limit the internal state to 1
> Head table fixes

- src/js/components/Filter.js
- src/js/utils/ui.js
- src/test/FilterTest.js
Rework dirty reducer so that it doesn't require state$ back into the model
Changed filter on output_filter in main Filter function to have the logic in model, cleaner and needed for the above mentioned changes
> Rework filter dirty state

- src/js/components/Table.js
By waiting for new input, the default stream came too late as it only updated after an API call was already made
> Use state directly to get default line amount for tables

- src/js/utils/ui.js
startWith was originally removed to solve an issue in the filter tests but this change is no longer needed
> Fix GSKCMP-57, prevent state updates by making sure dirty ui is pre-defined

- src/js/components/SampleTable/SampleInfo.js
Handle missing dose_unit or time_unit by printing "?" instead
Make entry and entrySmall more robust for invalid data by using optional chaining; we can't call .length on undefined
> Properly handle missing dose_unit or dose_time

- src/js/components/BinnedPlots/CorrelationPlot.js
- src/js/main.scss
- src/js/utils/utils.js
Create extra utils function to get both width and height of an element
set height of div to 65vh, so 65% of screen height
set maxHeight to 75vw, so 75% of screen width for tall screens so we don't get a very tall & narrow plot
> Tweak correlation plot to define the plot div better so the size can't bounce between two states

- deployments.json
- src/js/components/Check.js
- src/js/pages/adminSettings.js
Can be used to configure the correct threshold to declare the cluster being busy instead of a fixed value
> Add statistics duration field in deployments & admin page

- src/js/components/CorrelationForm.js
- src/js/components/SignatureForm.js
- src/js/components/TreatmentCheck.js
- src/js/main.scss
Simplifies color changes
Removes a bit of styling from the code
Allows Generic treatment form to be correctly styled without having to pass styling strings into sub-components
> Move workflow dependent coloring to the style sheet

- src/js/components/SignatureGenerator.js
For valid signatures:
- 1 input sample: These are the [amountOfGenes] significant genes from the selected sample.
- 2+ input samples: The intersection of the significant genes from the selected samples resulted in [amountOfGenes] genes.
- 0 input samples: No samples were selected and yet a valid signature was generated. Please create a bug report!
For invalid signatures:
- 1 input sample: The selected sample didn't return any significant genes from which to create a signature!
- 2+ input samples: The resulting signature is empty as there is no intersection of significant genes in the selected samples!
- 0 input samples: No samples were selected from which to create a signature!
> Display a message how the signature was created or why no signature was made

- src/js/components/SignatureGenerator.js
tested with PARP2 with 20 significant genes
by setting state.core.showLimit to: 
19 -> shows dots & 'Show more' button
20 -> shows full signature, no 'Show more' button
21 -> shows full signature, no 'Show more' button
> Fix SignatureGenerator displaying '...' even for small signatures

- src/js/components/SignatureGenerator.js
- src/js/index.js
- src/js/pages/genericTreatment.js
the extra updates either don't do anything useful or overwrite the loadingVdom so the user gets to see outdated information
Also add extra debouncing on the dirty UI logic as it could flash dirty-clean-dirty
> Prevent state changes to update signature vdom

- src/js/drivers/makeAutocompleteDriver.js
Autocomplete fills with wrong text, normally overwritten by vdom,
but when the autocompleted text is the same as the full text,
the autocomplete library updates to the full (wrong) text but our code isn't fired properly (as there is no more change)
and thus we can't properly overwrite it later.
Code from the autocomplete library:
let text = el.text().trim();
this.el.value = text;
this.$el.trigger('change');
this._resetAutocomplete();
this.close();
// Handle onAutocomplete callback.
if (typeof this.options.onAutocomplete === 'function') {
this.options.onAutocomplete.call(this, text);
}
So all we're adding is an extra
this.el.value = 'correct text'
> Force update of input field after autocomplete happened

- src/js/components/SampleSelection.js
When dose isn't a number or the dose unit is long, truncate the whole string
> Truncate dose when text is too long

- src/js/components/Table.js
State can glitch, especially when using the search queries.
This causes loading vdom to be output and directly being overwritten by init vdom
> Delay loading vdom by 100ms

- src/js/components/Filter.js
In disease & correlation WFs the input trigger comes instantaneously but the API for filter values is still under its way. This means that a regular samplecombine doesn't output the values
first combine input trigger and filter values and then samplecombine the search values
> Allow filter values API call coming in later than the input trigger

- src/js/drivers/makeClipboardDriver.js
Firefox doesn't implement 'clipboard-write' but also doesn't allow querying it
Catch the exception that gets thrown.
> Catch error thrown in permission query under Firefox

- src/js/pages/genericTreatment.js
Exporter encounters issues when taking 'toUpperCase' from an undefined variable,
so pass an empty string instead of an undefined
> Fix Exporter in generic WF

- CHANGELOG.md
- src/js/components/SignatureCheck.js
The material icons get included through an stylesheet link in index.html And somehow the include in this way caused issues where the font didn't actually get included but instead a line of text was getting linked
> Remove include of material icons from webpack-material-design-icons

- CHANGELOG.md
- src/js/components/SampleSelectionFilters.js
When a sample selection filter is removed by updating the samples with less available filters, the update needs to check if the data is even available
> Check filter data present when updating a sample selection filter

- CHANGELOG.md
- src/js/components/SampleTable/SampleInfo.js
Adding a listener behaves badly when there is a reload. Somehow it blocks the stream propagating to downstream after the reload
> Don't add a listener to block propagation but do it inline within the zoom logic

- CHANGELOG.md
- package.json
- src/js/components/Check.js
The filters API endpoint is fully cached while the statistics are only semi-cached.
This also removes the spark jobserver call and calculations on the average job duration.
> On index/landing page, the server responsiveness is checked by retrieving the filters instead of the statistics

- CHANGELOG.md
- package.json
- server.js
- serverConfiguration.js
`serverConfiguration.js` should contain valid information matching the deployment infrastructure
> Set the contentSecurityPolicy option in helmet to improve cross-site scripting security
