e2e/app.e2e-spec.ts, e2e/app.po.ts, karma.conf.js, package.json, src/app/actions/nav.ts, src/app/app.component.html, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/components/dashboard/dashboard.component.html, src/app/components/dashboard/dashboard.component.ts, src/app/reducers/index.ts, src/app/reducers/nav.ts
* Added e2e tests
* Small refactor
* Updated dependencies
=> Refactor update

package.json, src/app/app-routing.module.ts, src/app/app.module.ts
=> chore(ng-cli): angular-cli upgrade

src/js/components/SampleSelection.js
Using the new API call. Of course needs the updated LuciusAPI version too.
=> Use renamed API call compoundToSamples -> treatmentToPerturbations

src/js/components/BinnedPlots/HistogramSpec.js, src/js/components/BinnedPlots/SimilarityPlotSpec.js
Done for both Histograms and Similarity plots
=> Add plot names and axis names & tags

src/js/index.js, src/js/main.scss
Show text underline in navigation bar for the current page
=> Page identification

src/js/components/Table.js
Update default value logic to not just use fold but actually use last value to take difference
Still use fold though to have access to the old value but instead put old and new value in array
=> SampleTable defaultAmountToDisplay$ accumulator is still wrong

src/js/components/Filter.js
=> In Filter component Protocol should be rename to Cell

src/js/configuration.js, src/js/pages/adminSettings.js, src/js/pages/settings.js
Used to enable or disable the admin settings on the settings page
=> Add config field in settings to be able to tweak the functionality in the application

deployments.json, src/js/configuration.js, src/js/index.js, src/js/main.scss, src/js/pages/adminSettings.js, src/js/pages/settings.js
Make logo configurable in admin page, default setting in deployments
Made default logo one from Data-Intuitive
Other deployments are empty
=> A logo should be shown in the web interface

src/js/components/TreatmentForm.js
Default reducer in form was wrong
=> Fix ghost scenarios causing issues when url paths get changed

src/js/components/SampleSelection.js, src/js/components/SampleTable/SampleInfo.js
Additionally fix length difference in id truncation, happened in e137c16cc7e896c51e8fde8213ac5f11950da64c
Requires LuciusCore & LuciusWeb GSKCMP-68 branches to merged into their respective develop branches too
=> Display time unit and dose unit in tables

src/js/components/Statistics.js
protocol -> cell
concentration -> dose
compound -> treatment
=> Rename key words on the statistics page to new nomenclature

deployments.json, src/js/components/SampleTable/SampleInfo.js, src/js/components/TreatmentCheck.js, src/js/index.js, src/js/main.scss, src/js/pages/genericTreatment.js, src/js/pages/ligand.js
Started from 9091a1900f10331319c9694fa1f1f8db01ab956a for testability but ideally would be merged separately
=> Add Ligand Workflow

src/js/components/SignatureCheck.js
Change 'in L1000?' to 'found?'
Display 'Gene Space'
=> Display gene space during signature check

src/js/components/SampleTable/SampleInfo.js
=> Add TRT_OE as possible treatment to be displayed in the top tables

CHANGELOG.md, src/js/components/BinnedPlots/BinnedPlots.js, src/js/components/BinnedPlots/CorrelationPlot.js, src/js/components/Table.js, src/js/components/TreatmentCheck.js
Improve sturdiness against invalid input
=> Gskcmp 99 improve input validation

CHANGELOG.md, package.json, src/js/components/SampleSelection.js
Fix mistake in sample selection column truncation code
version bump to 5.0.2
=> Fix mistake in sample selection column truncation code

CHANGELOG.md, deployments.json, src/js/components/Filter.js, src/test/FilterTest.js
Filter functionality made dynamic so that new filter groups can be added as needed
=> Gskcmp 98 dynamic filter keys

CHANGELOG.md, deployments.json, src/js/index.js, src/js/pages/admin.js, src/js/pages/init.js, src/sass/_init.scss, src/sass/main.scss
Add browser access to restarting the API
=> Gskcmp 100 restart api

src/js/components/Exporter.js, src/js/drivers/makeFloatingActionButtonDriver.js
also handle rare condition of fab not being initialized when trying to update it
=> Use 'DOMContentLoaded' event as trigger to initialize FAB

src/js/components/SampleSelection.js, src/js/components/SampleSelectionFilters.js, src/js/components/TreatmentForm.js, src/js/drivers/makeSliderDriver.js, src/js/index.js, src/js/main.js, src/js/pages/genericTreatment.js, src/sass/_sample_selection_filters.scss, src/sass/main.scss, src/test/SampleSelectionTest.js
Add filters above the sample tables to reduce the available & unwanted options
=> Gskcmp 101 ability to filter sample tables

CHANGELOG.md, package-lock.json, package.json, src/js/components/AdminStatus.js, src/js/components/CompoundTable/CompoundInfo.js, src/js/components/GeneAnnotationQuery.js, src/js/components/SampleSelection.js, src/js/components/SampleTable/SampleInfo.js, src/js/components/SettingsEditor.js, src/js/components/SignatureGenerator.js, src/js/components/Statistics.js, src/js/components/Table.js, src/js/components/TargetForm.js, src/js/components/TreatmentAnnotation.js, src/js/index.js, src/js/pages/adminSettings.js, src/js/pages/correlation.js, src/js/pages/debug.js, src/js/pages/home.js, src/js/pages/init.js, src/js/pages/settings.js, src/js/pages/statistics.js, src/js/pages/target.js, src/js/utils/logger.js
fix merge being removed in favour of mergeRight and contains in favour of includes
Also removed various imports in several files that are no longer used
=> Update Ramda to 0.28.0
